Обновление sdk
Komtet/komtet-kassa-php-sdk pull request #10
Opened 2017-10-26 13:20 UTC by mini4

1. Добавлен менеджер задач
2. Добавлено необязательно поле id в класс Position

2017-10-26 13:35 UTC, Kilte commented
> The seven rules of a great Git commit message
>    Separate subject from body with a blank line
>    Limit the subject line to 50 characters
>    **Capitalize the subject line**
>    Do not end the subject line with a period
>    **Use the imperative mood in the subject line**
>    Wrap the body at 72 characters
>    Use the body to explain what and why vs. how

В идеале конечно лучше придерживаться всех, только я и сам их нарушаю. 
Но стоит хотя бы попытаться придерживаться единого стиля.
Т.е. будет что-то вроде "Add TaskManager" и по желанию в описание в двух словах можно добавить, зачем оно нужно. Ну и т.д.
Пока не торопись править, лучше перед мержем это сделать, т.к. скорее всего ещё правки по коду будут.

2017-10-26 13:42 UTC, ghost requested changes

2017-10-26 13:42 UTC, Kilte commented on src/TaskManager.php
> +class TaskManager
А почему отдельный класс? Можно было туда же, куда и все остальные обращения к api запихнуть.

2017-10-26 13:42 UTC, Kilte commented on src/TaskManager.php
> +    public function getTaskInfo($task_id)
camelCase

2017-10-26 13:42 UTC, Kilte commented on src/Position.php
> +    public function __construct($name, $price, $quantity, $total, $discount, Vat $vat, $id=null)
Слишком много аргументов. Т.к. $id опциональный, предлагаю удалить аргумент и добавить метод setId().

2017-10-26 13:52 UTC, mini4 commented on src/TaskManager.php
> +class TaskManager
Запихать то можно, но это менеджер очередей, как бы немного другое. Для получения задачи очередь не нужна.

2017-10-26 14:48 UTC, ghost requested changes

2017-10-26 14:48 UTC, Kilte commented on src/TaskManager.php
> +class TaskManager
Да, пожалуй лучше пусть так остаётся.

2017-10-26 14:48 UTC, Kilte commented on src/TaskManager.php
> +     * Gets info about the task
Gets -> Returns

2017-10-26 14:48 UTC, Kilte commented on src/TaskManager.php
> +     * @param string $task_id Task identificator
Здесь забыл аргумент переименовать. И вместо identificator лучше ID.

2017-10-26 14:48 UTC, Kilte commented on README.md
>  // Можно также установить единицу измерения:
"Можно также" "Можно также". Тогда в случае с measureName будет лучше написать  "и единицу измерения:"

2017-10-26 14:48 UTC, Kilte commented on README.md
> +Получить информацию о поставленной задачи на фискализацию:
задачи -> задаче

2017-10-26 14:48 UTC, Kilte commented on README.md
> +Получить информацию о поставленной задачи на фискализацию:
Не, даже так:
"Получить информацию о поставленной на фискализацию задаче:"

2017-10-26 14:48 UTC, Kilte commented on README.md
> +$task_manager = new TaskManager($client);
camelCase

2017-10-27 07:57 UTC, ghost approved these changes

2017-10-27 07:58 UTC, Kilte commented
Теперь было бы неплохо объединить последние два коммита с предыдущими изменениями и переписать сообщения коммитов.

2017-10-27 11:05 UTC, ghost requested changes

2017-10-27 11:05 UTC, Kilte commented on src/Position.php
> +    public function __construct($name, $price, $quantity, $total, $discount, Vat $vat, $id=null)
Аргумент так и остался

2017-10-27 11:31 UTC, merged