расширил sdk для работы с заказами и курьерами
Komtet/komtet-kassa-php-sdk pull request #33
Opened 2019-05-15 12:10 UTC by alexandrmotmom

2019-05-23 07:26 UTC, mini4 commented on src/Client.php
> +        if ($method == 'POST' or $method == 'PUT') {
```php
if (in_array($method, array('POST', 'PUT'))) {
    ...
}
```

2019-05-23 07:26 UTC, mini4 commented on src/Client.php
>          if ($data === null) {
Думаю, что так нагляднее будет
```php
if (is_array($data)) {
    $data = json_encode($data);
} elseif ($data) {
    throw new InvalidArgumentException('Unexpected type of $data, excepts array or null');
}

if (!$method):
    $method = $data !== null ? 'POST' : 'GET';
```

2019-05-23 07:45 UTC, alexandrmotmom commented on src/Client.php
>          if ($data === null) {
немного питона) 
```suggestion
        if (!$method):
```

2019-05-23 07:51 UTC, zeleng requested changes

2019-05-23 07:51 UTC, zeleng commented on src/Client.php
> +    public function sendRequest($path, $data = null, $method = null)
если нет такого, что $data - массив, но метод должен быть GET, то почему бы не поставить GET по умолчанию

2019-05-23 07:51 UTC, zeleng commented on src/Order.php
> +      if ($state !== null) {
не лишнее условие?

2019-05-23 07:51 UTC, zeleng commented on src/Order.php
> +  public function addCallbackUrl($callback_url)
setCallbackUrl

2019-05-23 07:51 UTC, zeleng commented on src/Order.php
> +  public function addCourierId($courier_id)
setCourierId

2019-05-24 06:09 UTC, alexandrmotmom commented on src/Order.php
> +      if ($state !== null) {
Это почему оно лишнее?

2019-05-24 06:31 UTC, zeleng commented on src/Order.php
> +      if ($state !== null) {
атрибут класса у тебя уже есть и уже null. и значение по умолчанию задается в конструкторе. и получается что условием ты проверяешь если значение передано, то его применить. а если не передано, то не применять null по умолчанию, а оставить null, который был при создании.

2019-05-24 06:34 UTC, alexandrmotmom commented on src/Client.php
> +    public function sendRequest($path, $data = null, $method = null)
Поломаем структура, предложенную Костей выше.

2019-05-24 07:15 UTC, keipaglows approved these changes

2019-05-24 08:31 UTC, zeleng commented on src/Client.php
> +    public function sendRequest($path, $data = null, $method = null)
в его предложении этот случай не учитывается и метод определяется от наличия даты, как раньше. на сколько я понимаю, ты и затеял это изменение чтобы можно было передавать в метод параметры архивом и делать потом get-запрос?

2019-05-24 11:39 UTC, zeleng approved these changes

2019-05-27 05:34 UTC, mini4 commented on src/Client.php
> +        }elseif ($data) {
пробела не хватает `} elseif ($data) {`

2019-05-27 05:34 UTC, mini4 commented on src/Client.php
> +        if (!$method)
для ясности возьми блок условного выражения в фигурные скобки.

2019-05-27 05:34 UTC, mini4 commented on src/CourierManager.php
> +class CourierManager
проверь везде отступы. должны быть равны 4 пробелам

2019-05-28 06:13 UTC, mini4 commented on src/Client.php
> +        if (!$method){
не хватает пробела после условия `if (!$method) {`

2019-05-28 06:13 UTC, mini4 commented on src/Order.php
> +     *]
лишний символ `]`

2019-05-28 06:13 UTC, mini4 commented on src/OrderPosition.php
> +         $args['total'] = $args['price'] * $args['quantity'];
отступы

2019-05-28 08:35 UTC, mini4 commented on src/OrderManager.php
> +        if ($courier_id !== null){
пробел

2019-05-28 08:35 UTC, mini4 commented on src/OrderManager.php
> +        if ($date_start !== null){
пробел

2019-05-28 08:45 UTC, mini4 approved these changes

2019-05-28 08:46 UTC, closed without merging