SDK сообщает если чек уже был отправлен клиенту
Komtet/komtet-kassa-php-sdk pull request #46
Opened 2019-08-07 15:28 UTC by alekciy

Суть проблемы которую призван решить данный PR.
При работе с сервисом через SDK внешний код может отловить возникший ClientException, но текст сообщения не информативный (в моём случае это "Unexpected status (422)") и мой код однозначно не может понять в чем проблема при работе с сервисом. А она может быть в том, что чек клиенту уже был послан (external_id: Чек с внешним идентификатором ХХХХХХ уже существует) и мой код может продолжить работу дальше. А сейчас приходится процесс остановить потому что не понятно, в чем конкретно была ошибка (и ситуацию приходится потом решать руками после анализа логов).

2019-09-06 11:58 UTC, mini4 requested changes

2019-09-06 11:58 UTC, mini4 commented on src/Exception/ClientException.php
> +    const EXTERNAL_ID_EXISTS = 1;
Я думаю, что нужно добавить новый класс исключения CheckExistsException наследник ClientException и вызывать его в случае совпадения шаблона ответа в методе sendRequest

2019-09-06 11:58 UTC, mini4 commented on CHANGELOG.rst
> +2.3.5 (07.08.2019)
Нет необходимости в заполнении CHANGELOG.rst и README.md, т.к. версия и дата фиксируется на момент релиза новой версии

2019-09-06 11:58 UTC, mini4 commented on src/Exception/ClientException.php
> +    const EXTERNAL_ID_EXISTS = 1;
Так же фича не будет принята без тестов

2019-09-11 11:13 UTC, alekciy commented on src/Exception/ClientException.php
> +    const EXTERNAL_ID_EXISTS = 1;
С `CheckExistsException` понятно. Но вот нормальный тест не получается. Сервер на POST запрос https://kassa.komtet.ru/api/shop/v1/queues/queue-id/task отвечает true даже если тестовый чек отправить два раза. Сам же тест я сделал в новом PR.

2019-09-11 11:19 UTC, alekciy commented
Закрываю в пользу https://github.com/Komtet/komtet-kassa-php-sdk/pull/49

2019-09-11 11:19 UTC, closed without merging